/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DegreeAttestationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getDegreeIdByHash"
      | "owner"
      | "registerDegree"
      | "revokeDegree"
      | "transferOwnership"
      | "verifyDegree"
      | "verifyHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DegreeRegistered"
      | "DegreeRevoked"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getDegreeIdByHash",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDegree",
    values: [string, string, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDegree",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDegree",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "verifyHash", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "getDegreeIdByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDegree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDegree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDegree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
}

export namespace DegreeRegisteredEvent {
  export type InputTuple = [
    degreeId: string,
    degreeHash: string,
    universityName: string,
    degreeName: string,
    graduationYear: string,
    attestationId: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    degreeId: string,
    degreeHash: string,
    universityName: string,
    degreeName: string,
    graduationYear: string,
    attestationId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    degreeId: string;
    degreeHash: string;
    universityName: string;
    degreeName: string;
    graduationYear: string;
    attestationId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DegreeRevokedEvent {
  export type InputTuple = [degreeId: string, timestamp: BigNumberish];
  export type OutputTuple = [degreeId: string, timestamp: bigint];
  export interface OutputObject {
    degreeId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DegreeAttestation extends BaseContract {
  connect(runner?: ContractRunner | null): DegreeAttestation;
  waitForDeployment(): Promise<this>;

  interface: DegreeAttestationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getDegreeIdByHash: TypedContractMethod<
    [degreeHash: string],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerDegree: TypedContractMethod<
    [
      degreeId: string,
      degreeHash: string,
      universityName: string,
      degreeName: string,
      graduationYear: string,
      attestationId: string
    ],
    [void],
    "nonpayable"
  >;

  revokeDegree: TypedContractMethod<[degreeId: string], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyDegree: TypedContractMethod<
    [degreeId: string],
    [
      [boolean, boolean, string, string, string, string, string, bigint] & {
        isValid: boolean;
        isRevoked: boolean;
        degreeHash: string;
        universityName: string;
        degreeName: string;
        graduationYear: string;
        attestationId: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  verifyHash: TypedContractMethod<
    [degreeHash: string],
    [[boolean, boolean] & { isRegistered: boolean; isActive: boolean }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getDegreeIdByHash"
  ): TypedContractMethod<[degreeHash: string], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDegree"
  ): TypedContractMethod<
    [
      degreeId: string,
      degreeHash: string,
      universityName: string,
      degreeName: string,
      graduationYear: string,
      attestationId: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeDegree"
  ): TypedContractMethod<[degreeId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyDegree"
  ): TypedContractMethod<
    [degreeId: string],
    [
      [boolean, boolean, string, string, string, string, string, bigint] & {
        isValid: boolean;
        isRevoked: boolean;
        degreeHash: string;
        universityName: string;
        degreeName: string;
        graduationYear: string;
        attestationId: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyHash"
  ): TypedContractMethod<
    [degreeHash: string],
    [[boolean, boolean] & { isRegistered: boolean; isActive: boolean }],
    "view"
  >;

  getEvent(
    key: "DegreeRegistered"
  ): TypedContractEvent<
    DegreeRegisteredEvent.InputTuple,
    DegreeRegisteredEvent.OutputTuple,
    DegreeRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DegreeRevoked"
  ): TypedContractEvent<
    DegreeRevokedEvent.InputTuple,
    DegreeRevokedEvent.OutputTuple,
    DegreeRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DegreeRegistered(string,string,string,string,string,string,uint256)": TypedContractEvent<
      DegreeRegisteredEvent.InputTuple,
      DegreeRegisteredEvent.OutputTuple,
      DegreeRegisteredEvent.OutputObject
    >;
    DegreeRegistered: TypedContractEvent<
      DegreeRegisteredEvent.InputTuple,
      DegreeRegisteredEvent.OutputTuple,
      DegreeRegisteredEvent.OutputObject
    >;

    "DegreeRevoked(string,uint256)": TypedContractEvent<
      DegreeRevokedEvent.InputTuple,
      DegreeRevokedEvent.OutputTuple,
      DegreeRevokedEvent.OutputObject
    >;
    DegreeRevoked: TypedContractEvent<
      DegreeRevokedEvent.InputTuple,
      DegreeRevokedEvent.OutputTuple,
      DegreeRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
