/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DegreeAttestation } from "./DegreeAttestation";
export * as factories from "./factories";
export { DegreeAttestation__factory } from "./factories/DegreeAttestation__factory";
